// ⚠️ 慎用！此脚本会清理旧数据

console.log('=== 存储清理工具 ===')
console.log('选择要执行的操作:')
console.log('')
console.log('1. 只清理草稿（保留商品）')
console.log('   wx.removeStorageSync("product_draft")')
console.log('')
console.log('2. 清理所有商品（保留草稿）')
console.log('   wx.removeStorageSync("mock_products")')
console.log('')
console.log('3. 查看所有存储的 key')
console.log('   wx.getStorageInfoSync().keys')
console.log('')
console.log('4. 清理购物车')
console.log('   wx.removeStorageSync("cart_items")')
console.log('')
console.log('5. 清理订单')
console.log('   wx.removeStorageSync("pending_orders")')
console.log('   wx.removeStorageSync("completed_orders")')
console.log('')
console.log('请复制上面的命令到控制台执行')
